# Generated by Django 4.2.7 on 2023-11-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='portada',
        ),
        migrations.AddField(
            model_name='juego',
            name='portada_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
